[build]
  command = "npm run build"
  publish = "dist"

[dev]
  targetPort = 3000

[[redirects]]
  from = "/gracias"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
